# Dependencies
markdown:       kramdown
highlighter:    rouge

kramdown:
  auto_ids:     true

# Permalinks
permalink:      pretty

# Server
source:         "."
baseurl:        ""
url:            "http://owlzone.org"
encoding:       UTF-8
exclude:
  - .git/
  - .github/
  - Gemfile
  - README.md

# Plugins

# Social
title:              OwlZone
description:        "The reign of a night owl."


# paginate
